### ISSUE TITLE
Password generation is not guaranteed to meet your requirements

### ISSUE THREAD

**Issue by mathiasprisfeldt** [NicholaiWP/PasswordGenerator#8]
The password generated is not guaranteed to meet your requirements.
All the checkboxes are not guaranteed to be met + the special characters you can type are also not guaranteed to be included.

**Comment by NicholaiWP** [comment]
As you previously suggested, maybe we should change the generation logic so that we for instance could get a password with equal weight on the marked options when generating a password. For instance:

16 characters long;
-4 special characters
- 4 uppercase chars
- 4 lowercase chars
- 4 numbers
OR have the option to randomize it  as well (as it is now). This would be more of an epic though and imo should be done when the other bugs are fixed and the app is in a good state.

**Comment by NicholaiWP** [comment]
@mathiasprisfeldt  I changed the logic to the following below, to ensure that when an option is checked, there's (atleast) 1 character for each 'category' so that the random generated password doesnt produce password that doesnt have a character you would expect from your checked option. It doesn't weight the options though. There's still not "equal" weight on the categories but i think this approach would be fine too. I could for instance add a feature to balance the weight. The special characters that can be typed is actually a 'limiter-field' that limits the available special characters
```

// Define character sets for each category
    const lowercaseChars:string = 'abcdefghijklmnopqrstuvwxyz';
    const uppercaseChars:string = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const numberChars:string = '0123456789';
    const specialChars:string = '-_+=!@#$%^&*()[]{}|;:,.<>?/';

    // Determine which categories to include based on user input
    const categories:string[] = [];

    if (useLowercase){
      categories.push(lowercaseChars);
    } 
    if (useUppercase){
      categories.push(uppercaseChars);
    } 
    if (useNumbers){
      categories.push(numberChars);
    } 
    if (useSpecialChars){
      categories.push(customSpecialChars ? customSpecialChars : specialChars);
    } 

    // Ensure that at least one character from each selected category is included
    let password:string = '';
    categories.forEach(category => {
      password += category.charAt(Math.floor(Math.random() * category.length));
    });

    // Add additional random characters to fill out the rest of the password
    while (password.length < length) {
      let category = categories[Math.floor(Math.random() * categories.length)];
      password += category.charAt(Math.floor(Math.random() * category.length));
    }


```
This code first defines character sets for each 'category' (lowercase letters, uppercase letters, numbers, and special characters). It then determines which categories to include in the password based on the user's input, and builds an array called categories containing the selected categories.

Next, the code ensures that at least one character from each selected category is included in the password. This is accomplished by looping through each category in the categories array, selecting a random character from that category, and adding it to the password string.

Finally, the code generates additional random characters to fill out the rest of the password length, until the desired length is reached.
